data:
  image: /root/to/brats/image
  train: data_list/brats/gen/train.csv
  valid: data_list/brats/gen/valid.csv
  test:  data_list/brats/gen/test.csv
  nomiss: False
  
seq2seq:
  ndims: 2                # 2D model
  c_s: 64                 # sequence code length
  c_w: 16                 # hyperconv weight length
  c_in: 3                 # input channels
  c_enc: [64, 128, 256]   # channels for encoder
  k_enc: [7, 3, 3]        # ksize for encoder
  s_enc: [1, 2, 2]        # strides for encoder
  nres_enc: 6             # number of resblocks in encoder
  norm: InstanceNorm      # normalization
  c_lstm: 256             # channels for convlstm
  c_dec: [128, 64, 3]     # channels for decoder
  k_dec: [3, 3, 7]        # ksize for decoder
  s_dec: [1, 1, 1]        # strides for decoder
  nres_dec: 6             # number of resblocks in decoder

train:
  epochs: 1000
  total_steps: 1000000
  lr: 2e-4
  rep_step: 8
  crop_size: [1, 192, 192]
  valid_size: [16, 192, 192]
  lambda_rec: 10
  lambda_per: 0.01
  lambda_cyc: 10
  vis_steps: 128
  ckpt_steps: 1280
  vis: vis/seq2seq/brats/2d
  ckpt: ckpt/seq2seq/brats/2d